### ISSUE TITLE
Complete initial CfM Project Startup checklist

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/WeCountCovid19#1]
- [X] setup github site
- [ ] apply for DPW site (https://digitalpublicworks.com/) - ask Amy once DPW gets started up?
- [ ] announce on MKE CfM slack. (Twitter too)
- [x] create google drive dir
- [ ] what am I missing?

**Comment by BarkleyBG** [comment]
google drive dir is here. I'll need to invite the WCC19 team to it individually. https://drive.google.com/drive/folders/18K0NRHrm7B2afUIBrSWaU6XauN2PSE8P
